/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankingApp.repository.entities;

import bankingApp.users.BankUser;
import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;



/**
 *
 * @author minon
 */

@Entity
@Table(name = "Bank_Transactions")
@NamedQueries({@NamedQuery(name = Transaction.GET_ALL_QUERY_NAME, query ="SELECT t from Transaction t")})

public class Transaction implements Serializable {
    
    public static final String GET_ALL_QUERY_NAME = "Transaction.getAll";
    
    //This is a autogenerated unique number
    private int transactionNumber;
    private String transactionName;
    private String transactionType;
    private String transactionDescription;
    
    //A transaction can only have one user 
    private BankUser bankUser;

    public Transaction() {
    }

    public Transaction(int transactionNumber, String transactionName, String transactionType, String transactionDescription, BankUser bankUser) {
        this.transactionNumber = transactionNumber;
        this.transactionName = transactionName;
        this.transactionType = transactionType;
        this.transactionDescription = transactionDescription;
        this.bankUser = bankUser;
    }
    
    

    @Id
    @GeneratedValue
    @Column(name = "transaction_ID")
    @NotNull
    public int getTransactionNumber() {
        return transactionNumber;
    }

    public void setTransactionNumber(int transactionNumber) {
        this.transactionNumber = transactionNumber;
    }
    @NotNull
    public String getTransactionName() {
        return transactionName;
    }

    public void setTransactionName(String transactionName) {
        this.transactionName = transactionName;
    }
    @NotNull
    public String getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    @NotNull
    public String getTransactionDescription() {
        return transactionDescription;
    }

    public void setTransactionDescription(String transactionDescription) {
        this.transactionDescription = transactionDescription;
    }
    
    //One transaction can only have one user 
    //The table will contain FK user_id
    //It cannot be left null
    @NotNull
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name = "Transaction_By_User_ID", nullable = false)
    public BankUser getBankUser() {
        return bankUser;
    }

    public void setBankUser(BankUser bankUser) {
        this.bankUser = bankUser;
    }
    
    
    
    
    
}
